role: select
twig_name: Select
examples:
  - id: default
    title: Country
    section: Examples
    props:
      name: country
    slot_twig: |
      <option value="">Choose…</option>
      <option value="de">Germany</option>
      <option value="at">Austria</option>
  - id: invalid
    title: Invalid
    section: States
    props:
      name: country
      invalid: true
    slot_twig: |
      <option value="">Choose…</option>
      <option value="de">Germany</option>
