role: textarea
twig_name: Textarea
examples:
  - id: default
    title: Default
    section: Examples
    props:
      name: "notes"
      placeholder: "Add a comment…"
    slot_text: ''
  - id: invalid
    title: Invalid
    section: States
    props:
      name: "notes"
      invalid: true
    slot_text: ''
